### ISSUE TITLE
BlockingDialogBox seems to wait for an extra click before it actually closes

### ISSUE THREAD

**Issue by Wavesonics** [jacopofar/godot-easy-dialogue#9]
Once all of the breaks are processed, I would expect the next click to dismiss it, but the next click apparently does nothing, then a second click will finally dismiss it.

Is this intended behavior? If so It'd be nice if it was configurable.

**Comment by Wavesonics** [comment]
In the demo code in this repo, the Blue guy's dialog exhibits this behavior.

**Comment by jacopofar** [comment]
Yes, in the demo for some of them I invoke manually `hide_box()` to avoid the extra click. The basic problem is that I don't want the dialogue to run in background while the player sees an input box or a selection.

I don't know exactly how to avoid it, the dialogue element sends a signal AND waits for input every time there's a break, a possible solution I thought about is to add a non-blocking break, something like `[signal blabla]` that unlike `[break blabla]` generates the signal but doesn't wait for the block.

The alternative is to do like I do now, and generate some "unblock" command in the caller (I don't like it tbh, the goal of the addon is to not have the developer worry about these details). Or to have some way to connect the three elements so that they maintain a state of what's already open and if you insert an input or choose an element from a list and a dialogue was running it also closes its break.

**Comment by Wavesonics** [comment]
so I realized i had an extra **[break]** at the end of my text, so like:
`"Line 1\n[break]Line 2[break]"`
Just removing the final break made it close without the extra click:
`"Line 1\n[break]Line 2"`

**Comment by jacopofar** [comment]
Oh nice! I think now that I merged your PR adding the closing signal without the need of a `[break]` tag this can be closed. Thank you!
